// <auto-generated />
using System;
using Ecommerce.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EcommerceDbContext))]
    partial class EcommerceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Ecommerce.Domain.Entities.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Ecommerce.Domain.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CartId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems", t =>
                        {
                            t.HasCheckConstraint("CK_CartItems_Quantity_Positive", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("Ecommerce.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", t =>
                        {
                            t.HasCheckConstraint("CK_Orders_Total_NonNegative", "\"Total\" >= 0");
                        });
                });

            modelBuilder.Entity("Ecommerce.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", t =>
                        {
                            t.HasCheckConstraint("CK_OrderItems_Price_Positive", "\"Price\" > 0");

                            t.HasCheckConstraint("CK_OrderItems_Quantity_Positive", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("Ecommerce.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Products", t =>
                        {
                            t.HasCheckConstraint("CK_Products_Price_Positive", "\"Price\" > 0");

                            t.HasCheckConstraint("CK_Products_Stock_NonNegative", "\"Stock\" >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "SNK-WHT-07-001",
                            Color = "White",
                            Description = "Tenis urbanos blancos para uso diario.",
                            ImageUrl = "https://placehold.co/600x400?text=White+Sneaker+7",
                            Name = "Urban Runner White 7",
                            Price = 179900m,
                            Size = 7,
                            Stock = 15
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "SNK-BLK-07-002",
                            Color = "Black",
                            Description = "Tenis negros flexibles con suela liviana.",
                            ImageUrl = "https://placehold.co/600x400?text=Black+Sneaker+7",
                            Name = "Street Flex Black 7",
                            Price = 189900m,
                            Size = 7,
                            Stock = 12
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Code = "SNK-GRY-08-003",
                            Color = "Gray",
                            Description = "Tenis grises comodos para caminatas largas.",
                            ImageUrl = "https://placehold.co/600x400?text=Gray+Sneaker+8",
                            Name = "Daily Move Gray 8",
                            Price = 169900m,
                            Size = 8,
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Code = "SNK-WHT-08-004",
                            Color = "White",
                            Description = "Tenis blancos minimalistas con acabado suave.",
                            ImageUrl = "https://placehold.co/600x400?text=White+Sneaker+8",
                            Name = "Clean Step White 8",
                            Price = 199900m,
                            Size = 8,
                            Stock = 10
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Code = "SNK-BLK-08-005",
                            Color = "Black",
                            Description = "Tenis negros casuales resistentes al uso frecuente.",
                            ImageUrl = "https://placehold.co/600x400?text=Black+Sneaker+8",
                            Name = "Night Walk Black 8",
                            Price = 209900m,
                            Size = 8,
                            Stock = 8
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Code = "SNK-GRY-09-006",
                            Color = "Gray",
                            Description = "Tenis grises de estilo deportivo urbano.",
                            ImageUrl = "https://placehold.co/600x400?text=Gray+Sneaker+9",
                            Name = "Metro Pace Gray 9",
                            Price = 219900m,
                            Size = 9,
                            Stock = 18
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Code = "SNK-WHT-09-007",
                            Color = "White",
                            Description = "Tenis blancos ligeros con plantilla acolchada.",
                            ImageUrl = "https://placehold.co/600x400?text=White+Sneaker+9",
                            Name = "Air Street White 9",
                            Price = 229900m,
                            Size = 9,
                            Stock = 14
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Code = "SNK-BLK-10-008",
                            Color = "Black",
                            Description = "Tenis negros clasicos con diseño versatil.",
                            ImageUrl = "https://placehold.co/600x400?text=Black+Sneaker+10",
                            Name = "Core Black 10",
                            Price = 239900m,
                            Size = 10,
                            Stock = 11
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Code = "SNK-GRY-10-009",
                            Color = "Gray",
                            Description = "Tenis grises con diseño sobrio para uso diario.",
                            ImageUrl = "https://placehold.co/600x400?text=Gray+Sneaker+10",
                            Name = "Balance Gray 10",
                            Price = 189900m,
                            Size = 10,
                            Stock = 16
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Code = "SNK-WHT-10-010",
                            Color = "White",
                            Description = "Tenis blancos clasicos para combinaciones casuales.",
                            ImageUrl = "https://placehold.co/600x400?text=White+Sneaker+10",
                            Name = "Classic White 10",
                            Price = 159900m,
                            Size = 10,
                            Stock = 22
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            Code = "SNK-GRY-07-011",
                            Color = "Gray",
                            Description = "Tenis grises livianos para jornadas activas.",
                            ImageUrl = "https://placehold.co/600x400?text=Gray+Sneaker+7",
                            Name = "Soft Track Gray 7",
                            Price = 174900m,
                            Size = 7,
                            Stock = 13
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            Code = "SNK-WHT-07-012",
                            Color = "White",
                            Description = "Tenis blancos con perfil bajo y suela flexible.",
                            ImageUrl = "https://placehold.co/600x400?text=White+Sneaker+7+Alt",
                            Name = "Fresh Walk White 7",
                            Price = 184900m,
                            Size = 7,
                            Stock = 9
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            Code = "SNK-BLK-08-013",
                            Color = "Black",
                            Description = "Tenis negros de ajuste comodo para uso urbano.",
                            ImageUrl = "https://placehold.co/600x400?text=Black+Sneaker+8+Alt",
                            Name = "Shadow Fit Black 8",
                            Price = 214900m,
                            Size = 8,
                            Stock = 17
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            Code = "SNK-GRY-08-014",
                            Color = "Gray",
                            Description = "Tenis grises con amortiguacion para caminar.",
                            ImageUrl = "https://placehold.co/600x400?text=Gray+Sneaker+8+Alt",
                            Name = "Cloud Step Gray 8",
                            Price = 204900m,
                            Size = 8,
                            Stock = 19
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000015"),
                            Code = "SNK-WHT-09-015",
                            Color = "White",
                            Description = "Tenis blancos minimalistas para combinaciones limpias.",
                            ImageUrl = "https://placehold.co/600x400?text=White+Sneaker+9+Alt",
                            Name = "Minimal White 9",
                            Price = 194900m,
                            Size = 9,
                            Stock = 21
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000016"),
                            Code = "SNK-BLK-09-016",
                            Color = "Black",
                            Description = "Tenis negros con acabado mate y suela resistente.",
                            ImageUrl = "https://placehold.co/600x400?text=Black+Sneaker+9",
                            Name = "Urban Core Black 9",
                            Price = 224900m,
                            Size = 9,
                            Stock = 12
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000017"),
                            Code = "SNK-GRY-09-017",
                            Color = "Gray",
                            Description = "Tenis grises versatiles para salidas casuales.",
                            ImageUrl = "https://placehold.co/600x400?text=Gray+Sneaker+9+Alt",
                            Name = "Route Gray 9",
                            Price = 199900m,
                            Size = 9,
                            Stock = 15
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000018"),
                            Code = "SNK-WHT-10-018",
                            Color = "White",
                            Description = "Tenis blancos con plantilla suave y estilo casual.",
                            ImageUrl = "https://placehold.co/600x400?text=White+Sneaker+10+Alt",
                            Name = "Pure Motion White 10",
                            Price = 234900m,
                            Size = 10,
                            Stock = 10
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000019"),
                            Code = "SNK-BLK-10-019",
                            Color = "Black",
                            Description = "Tenis negros de corte clasico para uso diario.",
                            ImageUrl = "https://placehold.co/600x400?text=Black+Sneaker+10+Alt",
                            Name = "Bold Step Black 10",
                            Price = 244900m,
                            Size = 10,
                            Stock = 7
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000020"),
                            Code = "SNK-GRY-10-020",
                            Color = "Gray",
                            Description = "Tenis grises con estructura estable y suela liviana.",
                            ImageUrl = "https://placehold.co/600x400?text=Gray+Sneaker+10+Alt",
                            Name = "City Flow Gray 10",
                            Price = 229900m,
                            Size = 10,
                            Stock = 18
                        });
                });

            modelBuilder.Entity("Ecommerce.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastNames")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ecommerce.Domain.Entities.Cart", b =>
                {
                    b.HasOne("Ecommerce.Domain.Entities.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("Ecommerce.Domain.Entities.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ecommerce.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("Ecommerce.Domain.Entities.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Domain.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ecommerce.Domain.Entities.Order", b =>
                {
                    b.HasOne("Ecommerce.Domain.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ecommerce.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Ecommerce.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Domain.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ecommerce.Domain.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Ecommerce.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Ecommerce.Domain.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Ecommerce.Domain.Entities.User", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
